import type { Metadata } from "next";
import { BaseLayout } from "@/components";
import "../globals.css";

export const metadata: Metadata = {
  title: "Sign In",
  description: "Generated by Blazar Labs",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <BaseLayout>{children}</BaseLayout>;
}
