import type { Metadata } from "next";
import { BaseLayout, CleanLayout } from "@/components";
import "../globals.css";

export const metadata: Metadata = {
  title: "App Name",
  description: "Generated by XXXXXX",
};

export default function ExplorerRootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <BaseLayout>{children}</BaseLayout>;
}
