import type { Metadata } from "next";
import { Khula } from "next/font/google";
import { ProtectedPage } from "@/components";
import { WineryProvider } from "@/context/wineryContext";
import "../globals.css";

const inter = Khula({
  weight: "400",
  style: "normal",
  display: "swap",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "App Name",
  description: "Generated by XXXXXX",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ProtectedPage>
      <WineryProvider>{children}</WineryProvider>
    </ProtectedPage>
  );
}
