import type { Metadata } from "next";
import { ExplorerLayout } from "@/components";
import "../globals.css";

export const metadata: Metadata = {
  title: "Explore",
  description: "Generated by Blazar Labs",
};

export default function ExplorerRootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <ExplorerLayout>{children}</ExplorerLayout>;
}
