import type { Metadata } from "next";
import { Khula } from "next/font/google";
import { Providers } from "@/context/Providers";
import "./globals.css";
import { Suspense } from "react";
import Loading from "./loading";

const inter = Khula({
  weight: "400",
  style: "normal",
  display: "swap",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Wine Portal",
  description: "Generated by Blazar Labs",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Suspense fallback={<Loading />}>{children}</Suspense>
        </Providers>
      </body>
    </html>
  );
}
