import type { Metadata } from "next";
import { Khula } from "next/font/google";
import { Providers } from "@/context/Providers";
import "./globals.css";

const inter = Khula({
  weight: "400",
  style: "normal",
  display: "swap",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "App Name",
  description: "Generated by XXXXXX",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
