import type { Metadata } from "next";
import { CleanLayout, ExplorerLayout } from "@/components";
import "../globals.css";

export const metadata: Metadata = {
  title: "App Name",
  description: "Generated by XXXXXX",
};

export default function PlaygroundRootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <CleanLayout>{children}</CleanLayout>;
}
